package compile_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/suite"

	rcfg "github.com/kalo-build/morphe-go/pkg/registry/cfg"
	"github.com/kalo-build/plugin-morphemap-ts/internal/testutils"
	"github.com/kalo-build/plugin-morphemap-ts/pkg/compile"
)

type CompileTestSuite struct {
	suite.Suite

	TestDirPath string

	ModelsDirPath     string
	EnumsDirPath      string
	StructuresDirPath string
	EntitiesDirPath   string
}

func TestCompileTestSuite(t *testing.T) {
	suite.Run(t, new(CompileTestSuite))
}

func (suite *CompileTestSuite) SetupTest() {
	suite.TestDirPath = testutils.GetTestDirPath()

	suite.ModelsDirPath = filepath.Join(suite.TestDirPath, "registry", "minimal", "models")
	suite.EnumsDirPath = filepath.Join(suite.TestDirPath, "registry", "minimal", "enums")
	suite.StructuresDirPath = filepath.Join(suite.TestDirPath, "registry", "minimal", "structures")
	suite.EntitiesDirPath = filepath.Join(suite.TestDirPath, "registry", "minimal", "entities")
}

func (suite *CompileTestSuite) TearDownTest() {
	suite.TestDirPath = ""
}

func (suite *CompileTestSuite) TestMorpheMapToTypeScript_FieldMap() {
	workingDirPath := filepath.Join(suite.TestDirPath, "working-ts-field")
	suite.Nil(os.Mkdir(workingDirPath, 0755))
	defer os.RemoveAll(workingDirPath)

	config := compile.TsConverterConfig{
		MapsPath: filepath.Join(suite.TestDirPath, "maps", "field"),
		RegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     suite.ModelsDirPath,
			RegistryEnumsDirPath:      suite.EnumsDirPath,
			RegistryStructuresDirPath: suite.StructuresDirPath,
			RegistryEntitiesDirPath:   suite.EntitiesDirPath,
		},
		OutputPath:            workingDirPath,
		SourceTypesImportPath: "@/types/models",
		TargetTypesImportPath: "@/types/models",
	}

	compileErr := compile.MorpheMapToTypeScript(config)

	suite.NoError(compileErr)

	// Verify generated TS file exists
	generatedPath := filepath.Join(workingDirPath, "org-self-map.ts")
	suite.FileExists(generatedPath)

	// Verify contents
	content, readErr := os.ReadFile(generatedPath)
	suite.NoError(readErr)
	contentStr := string(content)
	suite.Contains(contentStr, "import type { Organization }")
	suite.Contains(contentStr, "export function orgSelfMap")
	suite.Contains(contentStr, "Code generated by plugin-morphemap-ts")
}

func (suite *CompileTestSuite) TestMorpheMapToTypeScript_EnumMap() {
	workingDirPath := filepath.Join(suite.TestDirPath, "working-ts-enum")
	suite.Nil(os.Mkdir(workingDirPath, 0755))
	defer os.RemoveAll(workingDirPath)

	config := compile.TsConverterConfig{
		MapsPath: filepath.Join(suite.TestDirPath, "maps", "enum"),
		RegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     suite.ModelsDirPath,
			RegistryEnumsDirPath:      suite.EnumsDirPath,
			RegistryStructuresDirPath: suite.StructuresDirPath,
			RegistryEntitiesDirPath:   suite.EntitiesDirPath,
		},
		OutputPath:            workingDirPath,
		SourceTypesImportPath: "@/types/enums",
		TargetTypesImportPath: "@/types/enums",
	}

	compileErr := compile.MorpheMapToTypeScript(config)

	suite.NoError(compileErr)

	// Verify generated TS file exists
	generatedPath := filepath.Join(workingDirPath, "status-to-priority.ts")
	suite.FileExists(generatedPath)

	// Verify contents
	content, readErr := os.ReadFile(generatedPath)
	suite.NoError(readErr)
	contentStr := string(content)
	suite.Contains(contentStr, "const statusToPriorityMap: Record<string, string>")
	suite.Contains(contentStr, "export function statusToPriority")
	suite.Contains(contentStr, "throw new Error")
}

func (suite *CompileTestSuite) TestMorpheMapToTypeScript_NoMapsError() {
	emptyDir := filepath.Join(suite.TestDirPath, "working-ts-empty")
	suite.Nil(os.Mkdir(emptyDir, 0755))
	defer os.RemoveAll(emptyDir)

	mapsDir := filepath.Join(suite.TestDirPath, "working-ts-empty-maps")
	suite.Nil(os.Mkdir(mapsDir, 0755))
	defer os.RemoveAll(mapsDir)

	config := compile.TsConverterConfig{
		MapsPath: mapsDir,
		RegistryConfig: rcfg.MorpheLoadRegistryConfig{
			RegistryModelsDirPath:     suite.ModelsDirPath,
			RegistryEnumsDirPath:      suite.EnumsDirPath,
			RegistryStructuresDirPath: suite.StructuresDirPath,
			RegistryEntitiesDirPath:   suite.EntitiesDirPath,
		},
		OutputPath:            emptyDir,
		SourceTypesImportPath: "@/types/source",
		TargetTypesImportPath: "@/types/target",
	}

	compileErr := compile.MorpheMapToTypeScript(config)

	suite.Error(compileErr)
	suite.Contains(compileErr.Error(), "no .map files found")
}
