package compile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/kalo-build/morphe-go/pkg/registry"
	"github.com/kalo-build/plugin-morphemap-ts/pkg/mapdef"
)

// compileFieldMap generates a TypeScript converter function for a field map.
func compileFieldMap(m *mapdef.MorpheMap, localReg, externalReg *registry.Registry, config TsConverterConfig) error {
	data := BuildTsFieldMapData(m, config)

	content, err := RenderTsFieldMapTemplate(data)
	if err != nil {
		return fmt.Errorf("failed to render template: %w", err)
	}

	filename := toKebabCase(m.Name) + ".ts"
	filePath := filepath.Join(config.OutputPath, filename)

	if err := os.MkdirAll(config.OutputPath, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", filePath, err)
	}

	return nil
}

// TsFieldMapData holds the data for the field map TypeScript template.
type TsFieldMapData struct {
	ConverterName         string
	SourceType            string
	TargetType            string
	SourceTypesImportPath string
	TargetTypesImportPath string
	Fields                []TsFieldMappingData
	Hooks                 []string
}

// TsFieldMappingData holds a single field mapping entry for template rendering.
type TsFieldMappingData struct {
	TargetField string
	SourceExpr  string
	IsConstant  bool
	ConstValue  string
	Cast        string
	HasValueMap bool
	ValueMap    map[string]string
	Condition   string
}

// BuildTsFieldMapData constructs template data from a MorpheMap field map.
func BuildTsFieldMapData(m *mapdef.MorpheMap, config TsConverterConfig) TsFieldMapData {
	var sourceAlias, targetAlias string
	for _, alias := range sortedMapKeys(m.Aliases) {
		if targetAlias == "" {
			for key := range m.Fields {
				if strings.HasPrefix(key, alias+".") {
					targetAlias = alias
					break
				}
			}
		}
	}
	for _, alias := range sortedMapKeys(m.Aliases) {
		if alias != targetAlias {
			sourceAlias = alias
			break
		}
	}

	data := TsFieldMapData{
		ConverterName:         toCamelCase(m.Name),
		SourceType:            lastSegment(m.Aliases[sourceAlias]),
		TargetType:            lastSegment(m.Aliases[targetAlias]),
		SourceTypesImportPath: config.SourceTypesImportPath,
		TargetTypesImportPath: config.TargetTypesImportPath,
	}

	for key, val := range m.Fields {
		targetField := stripPrefix(key, targetAlias)

		fd := TsFieldMappingData{
			TargetField: toCamelCase(targetField),
		}

		if val.IsScalar {
			switch v := val.Scalar.(type) {
			case string:
				if strings.Contains(v, ".") && hasAlias(v, m.Aliases) {
					sourceField := stripPrefix(v, sourceAlias)
					fd.SourceExpr = toCamelCase(sourceField)
				} else {
					fd.IsConstant = true
					fd.ConstValue = fmt.Sprintf("'%s'", v)
				}
			case bool:
				fd.IsConstant = true
				fd.ConstValue = fmt.Sprintf("%t", v)
			case int:
				fd.IsConstant = true
				fd.ConstValue = fmt.Sprintf("%d", v)
			case float64:
				fd.IsConstant = true
				fd.ConstValue = fmt.Sprintf("%g", v)
			}
		} else if val.Object != nil {
			obj := val.Object
			sourceField := stripPrefix(obj.From, sourceAlias)
			fd.SourceExpr = toCamelCase(sourceField)
			fd.Cast = obj.Cast

			if len(obj.When) > 0 {
				var conditions []string
				for condKey, condVal := range obj.When {
					condField := toCamelCase(stripPrefix(condKey, targetAlias))
					conditions = append(conditions, fmt.Sprintf("target.%s === %v", condField, formatTsValue(condVal)))
				}
				fd.Condition = strings.Join(conditions, " && ")
			}
			if len(obj.ValueMap) > 0 {
				fd.HasValueMap = true
				fd.ValueMap = obj.ValueMap
			}
		}

		data.Fields = append(data.Fields, fd)
	}

	if m.Hooks != nil {
		for _, hook := range m.Hooks.AfterMap {
			data.Hooks = append(data.Hooks, hook.Name)
		}
	}

	return data
}

// RenderTsFieldMapTemplate renders a TypeScript converter file from template data.
func RenderTsFieldMapTemplate(data TsFieldMapData) (string, error) {
	tmpl, err := template.New("tsConverter").Parse(tsFieldMapTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

var tsFieldMapTemplate = `// Code generated by plugin-morphemap-ts. DO NOT EDIT.
import type { {{.SourceType}} } from '{{.SourceTypesImportPath}}';
import type { {{.TargetType}} } from '{{.TargetTypesImportPath}}';

/**
 * Converts a {{.SourceType}} to a {{.TargetType}}.
 */
export function {{.ConverterName}}(source: {{.SourceType}}): {{.TargetType}} {
  const target: Partial<{{.TargetType}}> = {};

{{- range .Fields}}
{{- if .IsConstant}}
  target.{{.TargetField}} = {{.ConstValue}};
{{- else if .Condition}}
  if ({{.Condition}}) {
    target.{{.TargetField}} = source.{{.SourceExpr}};
  }
{{- else if .Cast}}
  target.{{.TargetField}} = {{.Cast}}(source.{{.SourceExpr}}) as any;
{{- else if .HasValueMap}}
  const {{.TargetField}}Map: Record<string, string> = {
{{- range $src, $tgt := .ValueMap}}
    '{{$src}}': '{{$tgt}}',
{{- end}}
  };
  target.{{.TargetField}} = {{.TargetField}}Map[source.{{.SourceExpr}}] ?? source.{{.SourceExpr}};
{{- else if .SourceExpr}}
  target.{{.TargetField}} = source.{{.SourceExpr}};
{{- end}}
{{- end}}

  return target as {{.TargetType}};
}
{{- range .Hooks}}

// Hook: {{.}}
// Implement this function to handle cases that can't be expressed declaratively.
// export function {{.}}(source: {{$.SourceType}}, target: {{$.TargetType}}): {{$.TargetType}} {
//   // TODO: implement
//   return target;
// }
{{- end}}
`

// Helper functions

func stripPrefix(path string, alias string) string {
	prefix := alias + "."
	if strings.HasPrefix(path, prefix) {
		return path[len(prefix):]
	}
	return path
}

func hasAlias(value string, aliases map[string]string) bool {
	for alias := range aliases {
		if strings.HasPrefix(value, alias+".") {
			return true
		}
	}
	return false
}

func toCamelCase(s string) string {
	// Handle nested paths: Address.Street → address.street
	if strings.Contains(s, ".") {
		parts := strings.Split(s, ".")
		for i, p := range parts {
			parts[i] = toCamelCase(p)
		}
		return strings.Join(parts, ".")
	}
	if len(s) == 0 {
		return s
	}
	// Simple PascalCase → camelCase
	first := strings.ToLower(string(s[0]))
	return first + s[1:]
}

func toKebabCase(name string) string {
	var result strings.Builder
	for i, r := range name {
		if i > 0 && r >= 'A' && r <= 'Z' {
			prev := rune(name[i-1])
			if prev >= 'a' && prev <= 'z' {
				result.WriteRune('-')
			}
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}

func lastSegment(path string) string {
	parts := strings.Split(path, "/")
	return parts[len(parts)-1]
}

func sortedMapKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	for i := 0; i < len(keys); i++ {
		for j := i + 1; j < len(keys); j++ {
			if keys[i] > keys[j] {
				keys[i], keys[j] = keys[j], keys[i]
			}
		}
	}
	return keys
}

func formatTsValue(v interface{}) string {
	switch val := v.(type) {
	case string:
		return fmt.Sprintf("'%s'", val)
	case bool:
		return fmt.Sprintf("%t", val)
	default:
		return fmt.Sprintf("%v", val)
	}
}
