package compile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/kalo-build/plugin-morphemap-ts/pkg/mapdef"
)

// compileEnumMap generates TypeScript helper functions for enum entry translation.
func compileEnumMap(m *mapdef.MorpheMap, config TsConverterConfig) error {
	data := BuildTsEnumMapData(m, config)

	content, err := RenderTsEnumMapTemplate(data)
	if err != nil {
		return fmt.Errorf("failed to render enum map template: %w", err)
	}

	filename := toKebabCase(m.Name) + ".ts"
	filePath := filepath.Join(config.OutputPath, filename)

	if err := os.MkdirAll(config.OutputPath, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", filePath, err)
	}

	return nil
}

// TsEnumMapData holds the data for the enum map TypeScript template.
type TsEnumMapData struct {
	FunctionName string
	SourceType   string
	TargetType   string
	Entries      []TsEnumEntryData
}

// TsEnumEntryData holds a single enum entry mapping for template rendering.
type TsEnumEntryData struct {
	SourceEntry string
	TargetEntry string
}

// BuildTsEnumMapData constructs template data from a MorpheMap enum map.
func BuildTsEnumMapData(m *mapdef.MorpheMap, config TsConverterConfig) TsEnumMapData {
	aliases := sortedMapKeys(m.Aliases)

	var sourceAlias, targetAlias string
	if len(aliases) >= 2 {
		for key := range m.Entries {
			for _, alias := range aliases {
				if strings.HasPrefix(key, alias+".") {
					targetAlias = alias
					break
				}
			}
			if targetAlias != "" {
				break
			}
		}
		for _, alias := range aliases {
			if alias != targetAlias {
				sourceAlias = alias
				break
			}
		}
	}

	data := TsEnumMapData{
		FunctionName: toCamelCase(m.Name),
		SourceType:   lastSegment(m.Aliases[sourceAlias]),
		TargetType:   lastSegment(m.Aliases[targetAlias]),
	}

	for targetKey, sourceVal := range m.Entries {
		data.Entries = append(data.Entries, TsEnumEntryData{
			TargetEntry: stripPrefix(targetKey, targetAlias),
			SourceEntry: stripPrefix(sourceVal, sourceAlias),
		})
	}

	return data
}

// RenderTsEnumMapTemplate renders a TypeScript enum converter file from template data.
func RenderTsEnumMapTemplate(data TsEnumMapData) (string, error) {
	tmpl, err := template.New("tsEnumConverter").Parse(tsEnumMapTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

var tsEnumMapTemplate = `// Code generated by plugin-morphemap-ts. DO NOT EDIT.

/**
 * Enum translation map: {{.SourceType}} → {{.TargetType}}
 */
const {{.FunctionName}}Map: Record<string, string> = {
{{- range .Entries}}
  '{{.SourceEntry}}': '{{.TargetEntry}}',
{{- end}}
};

/**
 * Translates a {{.SourceType}} enum value to a {{.TargetType}} enum value.
 */
export function {{.FunctionName}}(source: string): string {
  const result = {{.FunctionName}}Map[source];
  if (result === undefined) {
    throw new Error(` + "`Unknown {{.SourceType}} value: ${source}`" + `);
  }
  return result;
}
`
